language: android
sudo: required
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools # https://github.com/travis-ci/travis-ci/issues/5049
    - tools # https://github.com/travis-ci/travis-ci/issues/6040
    - android-26
    - sys-img-armeabi-v7a-android-21
    - platform-tools
    - build-tools-26.0.1
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./.wait_for_emulator.sh
  - adb shell input keyevent 82 &

script:
  - ./gradlew :app:lintGoogleplayDebug
  - ./gradlew :app:connectedGoogleplayDebugAndroidTest
